ALTER TABLE public.addresses
ADD COLUMN IF NOT EXISTS full_name TEXT,
ADD COLUMN IF NOT EXISTS landmark TEXT,
ADD COLUMN IF NOT EXISTS post_office TEXT,
ADD COLUMN IF NOT EXISTS district TEXT,
ADD COLUMN IF NOT EXISTS state_code TEXT,
ADD COLUMN IF NOT EXISTS normalized_pincode TEXT,
ADD COLUMN IF NOT EXISTS pincode_source TEXT,
ADD COLUMN IF NOT EXISTS pincode_validated_at TIMESTAMPTZ;

